version: '1.0'
services:
  api:
    container_name: api-gateway
    restart: always
    build: ./api-gateway
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
  users:
    container_name: users
    restart: always
    build: ./users
    depends_on:
      - db
    ports:
      - ${USER_PORT}:${USER_PORT}
  products:
    container_name: products
    restart: always
    build: ./products
    depends_on:
      - db
    ports:
      - ${PRODUCT_PORT}:${PRODUCT_PORT}
  db:
    container_name: db
    image: postgres
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - data:/data/db
      - ./config/ddl.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  data: {}