version: '1.0'
services:
  api:
    container_name: api-gateway
    restart: always
    build: ./api-gateway
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    volumes:
      - images:/images
  users:
    container_name: users
    hostname: users
    restart: always
    build: ./users
    depends_on:
      - db
    ports:
      - ${USER_PORT}:${USER_PORT}
  products:
    container_name: products
    hostname: products
    restart: always
    build: ./products
    depends_on:
      - db
    ports:
      - ${PRODUCT_PORT}:${PRODUCT_PORT}
    volumes:
      - images:/images
  images-server:
    image: bdlss/iipsrv-openjpeg-docker
    container_name: images-server
    ports:
      - 5003:80
    volumes:
      - images:/var/www/localhost/images
  db:
    container_name: db
    image: postgres
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - data:/data/db
volumes:
  data: {}
  images: 
    driver: local
    driver_opts:
      type: none
      device: C:/images
      o: bind