version: '1.0'
services:
  api:
    container_name: api
    restart: always
    build: .
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    volumes:
      - './:/src'
  db:
    container_name: db
    image: postgres
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - data:/data/db
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  data: {}
  pgadmin: {}