version: '1.0'
services:
  api:
    container_name: api
    restart: always
    build: .
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    volumes:
      - './:/src'
  db:
    container_name: postgres
    image: postgres
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - data:/data/db
      - ./src/config/ddl.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  data: {}